### ISSUE TITLE
수박게임 공용 TODO(2)

### ISSUE THREAD

**Issue by GHeeJeon** [INU-Fake-Developers/watermelon-game-jihee#2]
- [x] 수박게임 제작의도(덕질, 기념일, 친목도모 등) 선정
- [x] 이미지 고르기
- [x] 고른 이미지 편집하기 - 포도
- [x] 고른 이미지 편집하기 - 앵두
- [x] 고른 이미지 편집하기 - 귤
- [x] 고른 이미지 편집하기 - 레몬
- [x] 고른 이미지 편집하기 - 키위
- [x] 고른 이미지 편집하기 - 토마토
- [x] 고른 이미지 편집하기 - 복숭아
- [x] 고른 이미지 편집하기 - 파인애플
- [x] 고른 이미지 편집하기 - 야자
- [x] 고른 이미지 편집하기 - 수박
- [x] 고른 이미지 편집하기 - 큰 수박
