### ISSUE TITLE
수박게임 공용 TODO(4)

### ISSUE THREAD

**Issue by GHeeJeon** [INU-Fake-Developers/watermelon-game-jihee#4]
- [x] 로컬 환경에서 테스트하기
- [x] 배경사진 변경
- [x] 우측 상단 사진 편집
- [x] 배포하기
- [x] 서비스 도메인 리드미에 추가하기
